version: "3"

volumes:
    db_data:

services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

  mongodata:
    image: tianon/true
    volumes:
      - db_data:/data/db