version: "3"

volumes:
    dbvolume:

services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbvolume:/data/db
    command: mongod

  dbstore:
    image: tianon/true
    volumes:
      - dbvolume:/data/db